# Thymeleaf settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Server settings
server.port=8080

# ログレベルの設定
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example.myapp=DEBUG

# ログファイルの設定
logging.file.name=logs/myapp.log
logging.file.path=logs
